CREATE SCHEMA enterprise;
CREATE SCHEMA sysusr;

CREATE TABLE sysusr.psn
(
    psn_id                   int4         NOT NULL,
    corp_cd                  bpchar(2) NOT NULL,
    cli_no                   bpchar(8) NOT NULL,
    bkdn                     bpchar(42) NOT NULL,
    rpt_bkdn                 bpchar(42) NULL,
    empl_id                  bpchar(50) NOT NULL,
    first_nm                 bpchar(40) NOT NULL,
    mid_nm                   bpchar(40) NULL,
    nick_nm                  bpchar(40) NULL,
    last_nm                  bpchar(40) NOT NULL,
    nm_suffix                bpchar(6) NULL,
    nm_prefix                bpchar(20) NULL,
    gender_cd                bpchar(1) NULL,
    birth_dt                 date NULL,
    job_title_nm             bpchar(40) NULL,
    job_class_nm             bpchar(40) NULL,
    job_level_nm             bpchar(40) NULL,
    empl_veh_elig_cd         int2         NOT NULL,
    empl_veh_elig_chng_dt    date NULL,
    driving_start_dt         date NULL,
    driving_end_dt           date NULL,
    drvr_lic_no              bpchar(25) NULL,
    drvr_lic_st_prov_cd      bpchar(2) NULL,
    drvr_lic_expir_dt        date NULL,
    national_tax_id          bpchar(20) NOT NULL,
    empl_stat_cd             int2         NOT NULL,
    empl_stat_chng_dt        date NULL,
    empl_hire_dt             date NULL,
    empl_term_dt             date NULL,
    foreign_svc_empl_ind     numeric(1) NULL,
    card_typ_cd              int2 NULL,
    credit_card_acct_no      bpchar(20) NULL,
    credit_card_expir_dt     date NULL,
    cardholder_nm            bpchar(120) NULL,
    selector_level_nm        bpchar(50) NULL,
    mvr_request_recv_dt      date NULL,
    reimb_pgm_ind            numeric(1) NULL,
    exempt_empl_ind          numeric(1) NULL,
    payroll_deduct_ind       numeric(1) NULL,
    psn_org_role_cd          int2         NOT NULL,
    cli_hr_no                bpchar(50) NOT NULL,
    audit_insert_dt          date         NOT NULL,
    audit_insert_tm          time(0)      NOT NULL,
    audit_insert_login       bpchar(30) NOT NULL,
    audit_insert_pgm         bpchar(30) NOT NULL,
    audit_update_dt          date NULL,
    audit_update_tm          time(0) NULL,
    audit_update_login       bpchar(30) NULL,
    audit_update_pgm         bpchar(30) NULL,
    tcv_audit_insert_date    timestamp(6) NOT NULL,
    tcv_audit_insert_userid  varchar(30)  NOT NULL,
    tcv_audit_insert_program varchar(30)  NOT NULL,
    tcv_audit_update_date    timestamp(6) NULL,
    tcv_audit_update_userid  varchar(30) NULL,
    tcv_audit_update_program varchar(30) NULL,
    CONSTRAINT psn_pkey PRIMARY KEY (psn_id),
    CONSTRAINT sysusr_psn_ak1 UNIQUE (cli_no, empl_id, corp_cd),
    CONSTRAINT ucliempcorp UNIQUE (cli_no, empl_id, corp_cd)
);

CREATE TABLE sysusr.psn_addr
(
    psn_id                   int4         NOT NULL,
    addr_typ_cd              int2         NOT NULL,
    addr_line1               bpchar(40) NOT NULL,
    addr_line2               bpchar(40) NULL,
    addr_line3               bpchar(40) NULL,
    addr_line4               bpchar(40) NULL,
    city_nm                  bpchar(40) NOT NULL,
    cnty_nm                  bpchar(40) NOT NULL,
    st_prov_abbr_cd          bpchar(2) NOT NULL,
    postcode                 bpchar(10) NOT NULL,
    iso_cntry_cd             bpchar(2) NOT NULL,
    pref_addr_ind            numeric(1)   NOT NULL,
    audit_insert_dt          date         NOT NULL,
    audit_insert_tm          time(0)      NOT NULL,
    audit_insert_login       bpchar(30) NOT NULL,
    audit_insert_pgm         bpchar(30) NOT NULL,
    audit_update_dt          date NULL,
    audit_update_tm          time(0) NULL,
    audit_update_login       bpchar(30) NULL,
    audit_update_pgm         bpchar(30) NULL,
    tcv_audit_insert_date    timestamp(6) NOT NULL,
    tcv_audit_insert_userid  varchar(30)  NOT NULL,
    tcv_audit_insert_program varchar(30)  NOT NULL,
    tcv_audit_update_date    timestamp NULL,
    tcv_audit_update_userid  varchar(30) NULL,
    tcv_audit_update_program varchar(30) NULL,
    CONSTRAINT psn_addr_pkey PRIMARY KEY (psn_id, addr_typ_cd)
);

CREATE TABLE sysusr.psn_comm
(
    psn_id                   int4         NOT NULL,
    comm_typ_cd              int2         NOT NULL,
    comm_val                 bpchar(80) NOT NULL,
    comm_mask                bpchar(80) NOT NULL,
    ext_pager_pin            bpchar(20) NULL,
    pref_mthd_ind            numeric(1)   NOT NULL,
    audit_insert_dt          date         NOT NULL,
    audit_insert_tm          time(0)      NOT NULL,
    audit_insert_login       bpchar(30) NOT NULL,
    audit_insert_pgm         bpchar(30) NOT NULL,
    audit_update_dt          date NULL,
    audit_update_tm          time(0) NULL,
    audit_update_login       bpchar(30) NULL,
    audit_update_pgm         bpchar(30) NULL,
    tcv_audit_insert_date    timestamp(6) NOT NULL,
    tcv_audit_insert_userid  varchar(30)  NOT NULL,
    tcv_audit_insert_program varchar(30)  NOT NULL,
    tcv_audit_update_date    timestamp(6) NULL,
    tcv_audit_update_userid  varchar(30) NULL,
    tcv_audit_update_program varchar(30) NULL,
    CONSTRAINT psn_comm_pkey PRIMARY KEY (psn_id, comm_typ_cd)
);

CREATE TABLE sysusr.psn_chng_hist
(
    psn_id                   int4         NOT NULL,
    psn_data_cd              int2         NOT NULL,
    chng_dt                  date         NOT NULL,
    chng_tm                  time(0)      NOT NULL,
    chng_from_val            bpchar(255) NOT NULL,
    chng_to_val              bpchar(255) NOT NULL,
    audit_insert_login       bpchar(30) NOT NULL,
    audit_insert_login_nm    bpchar(60) NOT NULL,
    audit_insert_pgm         bpchar(30) NOT NULL,
    tcv_audit_insert_date    timestamp(6) NOT NULL,
    tcv_audit_insert_userid  varchar(30)  NOT NULL,
    tcv_audit_insert_program varchar(30)  NOT NULL,
    tcv_audit_update_date    timestamp(6) NULL,
    tcv_audit_update_userid  varchar(30) NULL,
    tcv_audit_update_program varchar(30) NULL,
    CONSTRAINT psn_chng_hist_pkey PRIMARY KEY (psn_id, psn_data_cd, chng_dt, chng_tm, chng_from_val, chng_to_val,
                                               audit_insert_login, audit_insert_login_nm, audit_insert_pgm)
);

CREATE TABLE sysusr.driver
(
    driv_nm_last             bpchar(20) NOT NULL,
    driv_nm_first            bpchar(15) NOT NULL,
    driv_nm_midinit          bpchar(1) NOT NULL,
    driv_nm_midrest          bpchar(14) NOT NULL,
    cli_driv_no              bpchar(20) NOT NULL,
    company_name             bpchar(45) NOT NULL,
    driv_addr1               bpchar(30) NOT NULL,
    driv_addr2               bpchar(30) NOT NULL,
    driv_city                bpchar(20) NOT NULL,
    driv_cnty                bpchar(23) NOT NULL,
    driv_state               bpchar(2) NOT NULL,
    driv_zipcode             bpchar(9) NOT NULL,
    driv_phone_area          bpchar(3) NOT NULL,
    driv_phone_no            bpchar(7) NOT NULL,
    driv_phone_extn          bpchar(4) NOT NULL,
    corp_cd                  bpchar(2) NOT NULL,
    client_no                bpchar(8) NOT NULL,
    unit_no                  bpchar(8) NOT NULL,
    soundex_last             bpchar(4) NOT NULL,
    soundex_first            bpchar(4) NOT NULL,
    tcv_audit_insert_date    timestamp(6) NOT NULL,
    tcv_audit_insert_userid  varchar(30)  NOT NULL,
    tcv_audit_insert_program varchar(30)  NOT NULL,
    tcv_audit_update_date    timestamp(6) NULL,
    tcv_audit_update_userid  varchar(30) NULL,
    tcv_audit_update_program varchar(30) NULL,
    CONSTRAINT driver_pkey PRIMARY KEY (client_no, unit_no)
);

CREATE TABLE sysusr.mast_unit_fin
(
    dlr_asgn_no              bpchar(9) NOT NULL,
    corp_cd                  bpchar(2) NOT NULL,
    client_no                bpchar(8) NOT NULL,
    bkdn                     bpchar(42) NOT NULL,
    unit_no                  bpchar(8) NOT NULL,
    cli_ast_no               bpchar(15) NOT NULL,
    pur_typ_cd               bpchar(2) NOT NULL,
    loc_st_cd                bpchar(2) NOT NULL,
    loc_city_cd              bpchar(4) NOT NULL,
    loc_cnty_cd              bpchar(3) NOT NULL,
    cont_no                  bpchar(11) NOT NULL,
    cont_typ                 bpchar(2) NOT NULL,
    lse_typ                  bpchar(1) NOT NULL,
    cli_yr_end               bpchar(4) NOT NULL,
    acc_mgt_svc_ind          bpchar(1) NOT NULL,
    flt_adm_svc_ind          bpchar(1) NOT NULL,
    flt_svc_ind              bpchar(1) NOT NULL,
    reimb_svc_ind            bpchar(1) NOT NULL,
    veh_rpt_svc_ind          bpchar(1) NOT NULL,
    cpn_bk_ind               bpchar(1) NOT NULL,
    mrm_svc_ind              bpchar(1) NOT NULL,
    fuel_svc_ind             bpchar(1) NOT NULL,
    ec_svc_ind               bpchar(1) NOT NULL,
    ins_svc_ind              bpchar(1) NOT NULL,
    bkdn_chrg_ind            bpchar(1) NOT NULL,
    rerg_svc_ind             bpchar(1) NOT NULL,
    bas_inv_amt              numeric(10, 2) NOT NULL,
    bas_inv_amt_typ          bpchar(3) NOT NULL,
    hldb_amt                 numeric(11, 2) NOT NULL,
    sl_tax_amt               numeric(11, 2) NOT NULL,
    cli_prc_amt              numeric(11, 2) NOT NULL,
    unit_prc_amt             numeric(9, 2)  NOT NULL,
    vnd_inv_amt              numeric(10, 2) NOT NULL,
    rebat_amt                numeric(11, 2) NOT NULL,
    drv_pd_opt_amt           numeric(7, 2)  NOT NULL,
    intrm_int_ind            bpchar(1) NOT NULL,
    tot_cap_cst              numeric(10, 2) NOT NULL,
    tot_aqstn_cst            numeric(10, 2) NOT NULL,
    lndr_no                  bpchar(5) NOT NULL,
    lsor_no                  bpchar(5) NOT NULL,
    fin_src                  bpchar(4) NOT NULL,
    fs_int_rt_ind            bpchar(4) NOT NULL,
    src_of_fnd               bpchar(3) NOT NULL,
    rnt_tax_pay_cd           bpchar(1) NOT NULL,
    bs_cst                   numeric(10, 2) NOT NULL,
    bs_typ                   bpchar(1) NOT NULL,
    cur_bk_val               numeric(10, 2) NOT NULL,
    cur_odom                 bpchar(7) NOT NULL,
    cur_odom_c               numeric(2)     NOT NULL,
    cur_odom_yr              numeric(2)     NOT NULL,
    cur_odom_mo              numeric(2)     NOT NULL,
    cur_odom_da              numeric(2)     NOT NULL,
    in_svc_c                 numeric(2)     NOT NULL,
    in_svc_yr                numeric(2)     NOT NULL,
    in_svc_mo                numeric(2)     NOT NULL,
    in_svc_da                numeric(2)     NOT NULL,
    mo_in_svc                numeric(3)     NOT NULL,
    calc_pref_cd             bpchar(2) NOT NULL,
    cum_dif_ind              bpchar(1) NOT NULL,
    lse_term                 bpchar(3) NOT NULL,
    lse_bill_cyc             bpchar(3) NOT NULL,
    lse_rt_typ               bpchar(2) NOT NULL,
    lse_int_rt               numeric(8, 6)  NOT NULL,
    int_rt_max               numeric(8, 6)  NOT NULL,
    pref_int_rt_ind          bpchar(4) NOT NULL,
    prc_sbsdy                numeric(9, 6)  NOT NULL,
    bill_int_rt_ind          bpchar(4) NOT NULL,
    lndr_yr_cd               bpchar(1) NOT NULL,
    prc_id                   bpchar(6) NOT NULL,
    prc_eff_c                numeric(2)     NOT NULL,
    prc_eff_yr               numeric(2)     NOT NULL,
    prc_eff_mo               numeric(2)     NOT NULL,
    prc_eff_da               numeric(2)     NOT NULL,
    var_prc_ind              bpchar(1) NOT NULL,
    lse_depr_ovrd            numeric(8, 6)  NOT NULL,
    adj_depr_pct             numeric(8, 6)  NOT NULL,
    init_rnt_c               numeric(2)     NOT NULL,
    init_rnt_yr              numeric(2)     NOT NULL,
    init_rnt_mo              numeric(2)     NOT NULL,
    init_rnt_da              numeric(2)     NOT NULL,
    lst_rnt_c                numeric(2)     NOT NULL,
    lst_rnt_yr               numeric(2)     NOT NULL,
    lst_rnt_mo               numeric(2)     NOT NULL,
    lst_rnt_da               numeric(2)     NOT NULL,
    init_bill_c              numeric(2)     NOT NULL,
    init_bill_yr             numeric(2)     NOT NULL,
    init_bill_mo             numeric(2)     NOT NULL,
    init_bill_da             numeric(2)     NOT NULL,
    lst_bill_c               numeric(2)     NOT NULL,
    lst_bill_yr              numeric(2)     NOT NULL,
    lst_bill_mo              numeric(2)     NOT NULL,
    lst_bill_da              numeric(2)     NOT NULL,
    era_svc_ind              bpchar(1) NOT NULL,
    itc_pct                  numeric(8, 6)  NOT NULL,
    incc_svc_ind             bpchar(1) NOT NULL,
    inpl_svc_ind             bpchar(1) NOT NULL,
    mgt_fee                  numeric(10, 6) NOT NULL,
    mgt_fee_ind              bpchar(1) NOT NULL,
    addl_mgt_fee             numeric(10, 6) NOT NULL,
    addl_mgt_ind             bpchar(1) NOT NULL,
    mgt_fee_max              numeric(11, 2) NOT NULL,
    post_term_fee            numeric(11, 6) NOT NULL,
    post_term_ind            bpchar(1) NOT NULL,
    rsdl_bk_val              numeric(11, 3) NOT NULL,
    lst_mo_amrt              numeric(9, 3)  NOT NULL,
    cur_mo_amrt              numeric(9, 3)  NOT NULL,
    nxt_mo_amrt              numeric(9, 3)  NOT NULL,
    ytd_amrt                 numeric(10, 3) NOT NULL,
    cli_ytd_amrt             numeric(10, 3) NOT NULL,
    ltd_amrt                 numeric(11, 3) NOT NULL,
    lst_mo_int               numeric(12, 3) NOT NULL,
    cur_mo_int               numeric(8, 3)  NOT NULL,
    nxt_mo_int               numeric(12, 3) NOT NULL,
    ytd_int                  numeric(9, 3)  NOT NULL,
    cli_ytd_int              numeric(9, 3)  NOT NULL,
    ltd_int                  numeric(10, 3) NOT NULL,
    lst_mo_rnt_tax           numeric(12, 3) NOT NULL,
    cur_mo_rnt_tax           numeric(12, 3) NOT NULL,
    nxt_mo_rnt_tax           numeric(12, 3) NOT NULL,
    ytd_rnt_tax              numeric(10, 3) NOT NULL,
    cli_ytd_rnt_tax          numeric(10, 3) NOT NULL,
    ltd_rnt_tax              numeric(10, 3) NOT NULL,
    lst_mo_mgt_fee           numeric(12, 3) NOT NULL,
    cur_mo_mgt_fee           numeric(12, 3) NOT NULL,
    nxt_mo_mgt_fee           numeric(12, 3) NOT NULL,
    ytd_mgt_fee              numeric(12, 3) NOT NULL,
    cli_ytd_mgt_fee          numeric(12, 3) NOT NULL,
    ltd_mgt_fee              numeric(9, 3)  NOT NULL,
    phh_split                numeric(9, 6)  NOT NULL,
    sell_fee                 numeric(11, 2) NOT NULL,
    tot_cown_bill            numeric(10, 2) NOT NULL,
    otr_amrt                 numeric(10, 2) NOT NULL,
    cum_dif                  numeric(11, 2) NOT NULL,
    ytd_int_var              numeric(11, 2) NOT NULL,
    cmpnd_int                numeric(11, 2) NOT NULL,
    otr_c                    numeric(2)     NOT NULL,
    otr_yr                   numeric(2)     NOT NULL,
    otr_mo                   numeric(2)     NOT NULL,
    otr_da                   numeric(2)     NOT NULL,
    sl_typ                   bpchar(2) NOT NULL,
    sl_c                     numeric(2)     NOT NULL,
    sl_yr                    numeric(2)     NOT NULL,
    sl_mo                    numeric(2)     NOT NULL,
    sl_da                    numeric(2)     NOT NULL,
    sl_amt                   numeric(10, 2) NOT NULL,
    sld_tax_amt              numeric(10, 2) NOT NULL,
    sld_tax_loc              bpchar(9) NOT NULL,
    fin_hst_cr_c             numeric(2)     NOT NULL,
    fin_hst_cr_yr            numeric(2)     NOT NULL,
    fin_hst_cr_mo            numeric(2)     NOT NULL,
    fin_hst_cr_da            numeric(2)     NOT NULL,
    bkdn_eff_c               numeric(2)     NOT NULL,
    bkdn_eff_yr              numeric(2)     NOT NULL,
    bkdn_eff_mo              numeric(2)     NOT NULL,
    bkdn_eff_da              numeric(2)     NOT NULL,
    cli_pd_opt_amt           numeric(11, 2) NOT NULL,
    ir_svc_ind               bpchar(1) NOT NULL,
    interim_rent_ind         bpchar(1) NOT NULL,
    rt_attr_c                numeric(2)     NOT NULL,
    rt_attr_yr               numeric(2)     NOT NULL,
    rt_attr_mo               numeric(2)     NOT NULL,
    rt_attr_da               numeric(2)     NOT NULL,
    pu_svc_ind               bpchar(1) NOT NULL,
    ext_lease_ind            bpchar(1) NOT NULL,
    unit_addl_int_amt        numeric(12, 2) NOT NULL,
    addl_int_effdt_cc        bpchar(2) NOT NULL,
    addl_int_effdt_yy        bpchar(2) NOT NULL,
    addl_int_effdt_mm        bpchar(2) NOT NULL,
    addl_int_effdt_dd        bpchar(2) NOT NULL,
    fund_ind                 bpchar(1) NOT NULL,
    cap_freeze_ind           bpchar(1) NOT NULL,
    term_type                bpchar(2) NOT NULL,
    maturity_date_cc         bpchar(2) NOT NULL,
    maturity_date_yy         bpchar(2) NOT NULL,
    maturity_date_mm         bpchar(2) NOT NULL,
    maturity_date_dd         bpchar(2) NOT NULL,
    tcv_audit_insert_date    timestamp(6)   NOT NULL,
    tcv_audit_insert_userid  varchar(30)    NOT NULL,
    tcv_audit_insert_program varchar(30)    NOT NULL,
    tcv_audit_update_date    timestamp(6) NULL,
    tcv_audit_update_userid  varchar(30) NULL,
    tcv_audit_update_program varchar(30) NULL
);

CREATE TABLE sysusr.mast_unit_ext
(
    dlr_asgn_no                bpchar(9) NOT NULL,
    corp_cd                    bpchar(2) NOT NULL,
    curr_odom                  numeric(7) NULL,
    curr_odom_dt               date NULL,
    curr_odom_src              bpchar(1) NULL,
    curr_odom_uom_cd           bpchar(2) NULL,
    asgn_stat_cd               bpchar(1) NULL,
    asgn_stat_dt               date NULL,
    reassign_dt                date NULL,
    competitor_org_id          int4 NULL,
    competitor_unit_no         bpchar(20) NULL,
    notify_competitor_sold_ind numeric(1) NULL,
    alt_unit_no                bpchar(20) NULL,
    tag_typ_cd                 int2 NULL,
    title_issue_cd             int2 NULL,
    phh_title_dt               date NULL,
    title_loc_cd               int2 NULL,
    title_out_rsn_cd           int2 NULL,
    title_retention_cli_ind    numeric(1) NULL,
    cli_stat_title_ind         numeric(1) NULL,
    cli_stat_bill_of_sale_ind  numeric(1) NULL,
    cli_stat_tax_afd_ind       numeric(1) NULL,
    cli_title_mail_dt          date NULL,
    lien_ind                   numeric(1) NULL,
    po_no                      bpchar(20) NULL,
    prod_sub_class_cd          bpchar(2) NULL,
    bus_mfg_cd                 bpchar(2) NULL,
    hazmat_carrier_ind         numeric(1) NULL,
    audit_insert_dt            date         NOT NULL,
    audit_insert_tm            time(0)      NOT NULL,
    audit_insert_login         bpchar(30) NULL,
    audit_insert_pgm           bpchar(30) NOT NULL,
    audit_update_dt            date NULL,
    audit_update_tm            time(0) NULL,
    audit_update_login         bpchar(30) NULL,
    audit_update_pgm           bpchar(30) NULL,
    tcv_audit_insert_date      timestamp(6) NOT NULL,
    tcv_audit_insert_userid    varchar(30)  NOT NULL,
    tcv_audit_insert_program   varchar(30)  NOT NULL,
    tcv_audit_update_date      timestamp(6) NULL,
    tcv_audit_update_userid    varchar(30) NULL,
    tcv_audit_update_program   varchar(30) NULL,
    cgm_ast_ind                bpchar(1) NOT NULL DEFAULT 'N'::bpchar
);

CREATE TABLE sysusr.mast_unit
(
    client_no                bpchar(8) NOT NULL,
    corp_cd                  bpchar(2) NOT NULL,
    unit_no                  bpchar(8) NOT NULL,
    cli_ast_no               bpchar(15) NOT NULL,
    repl_client_no           bpchar(8) NOT NULL,
    repl_unit_no             bpchar(8) NOT NULL,
    repl_cli_ast_no          bpchar(15) NOT NULL,
    cur_evt_seq_no           numeric(4)     NOT NULL,
    cur_evt                  bpchar(10) NOT NULL,
    cur_evt_dt_c             numeric(2)     NOT NULL,
    cur_evt_dt_yr            numeric(2)     NOT NULL,
    cur_evt_dt_mo            numeric(2)     NOT NULL,
    cur_evt_dt_da            numeric(2)     NOT NULL,
    reqsn_no                 bpchar(7) NOT NULL,
    cont_typ_cd              bpchar(2) NOT NULL,
    mo_reqd                  bpchar(4) NOT NULL,
    emr_ind                  bpchar(1) NOT NULL,
    ttl_cert_st              bpchar(2) NOT NULL,
    bkdn                     bpchar(42) NOT NULL,
    ttl_own                  bpchar(45) NOT NULL,
    ttl_co_nm                bpchar(45) NOT NULL,
    ttl_own_1st              bpchar(15) NOT NULL,
    ttl_own_mi               bpchar(1) NOT NULL,
    ttl_own_midrest          bpchar(14) NOT NULL,
    ttl_own_lst              bpchar(20) NOT NULL,
    ttl_addr1                bpchar(30) NOT NULL,
    ttl_addr2                bpchar(30) NOT NULL,
    ttl_city                 bpchar(20) NOT NULL,
    ttl_cnty                 bpchar(23) NOT NULL,
    ttl_st                   bpchar(2) NOT NULL,
    ttl_zip                  bpchar(9) NOT NULL,
    ttl_no                   bpchar(15) NOT NULL,
    ttl_loc                  bpchar(1) NOT NULL,
    ttl_iss_dt_c             numeric(2)     NOT NULL,
    ttl_iss_dt_yr            numeric(2)     NOT NULL,
    ttl_iss_dt_mo            numeric(2)     NOT NULL,
    ttl_iss_dt_da            numeric(2)     NOT NULL,
    tag_no                   bpchar(20) NOT NULL,
    tag_iss_st               bpchar(2) NOT NULL,
    reg_xpir_dt_c            numeric(2)     NOT NULL,
    reg_xpir_dt_yr           numeric(2)     NOT NULL,
    reg_xpir_dt_mo           numeric(2)     NOT NULL,
    reg_xpir_dt_da           numeric(2)     NOT NULL,
    filler2                  bpchar(20) NOT NULL,
    filler3                  bpchar(15) NOT NULL,
    vin_decode_stat_cd       bpchar(1) NOT NULL,
    filler6                  bpchar(14) NOT NULL,
    cli_drv_no               bpchar(20) NOT NULL,
    filler7                  bpchar(20) NOT NULL,
    vndr_market_id           bpchar(2) NOT NULL,
    filler9                  bpchar(9) NOT NULL,
    uvc                      bpchar(10) NOT NULL,
    group_cd                 bpchar(4) NOT NULL,
    drv_strt_dt_c            numeric(2)     NOT NULL,
    drv_strt_dt_yr           numeric(2)     NOT NULL,
    drv_strt_dt_mo           numeric(2)     NOT NULL,
    drv_strt_dt_da           numeric(2)     NOT NULL,
    dlr_asgn_no              bpchar(9) NOT NULL,
    fac_ord_no               bpchar(12) NOT NULL,
    vin_1st_9                bpchar(9) NOT NULL,
    vin_10_11                bpchar(2) NOT NULL,
    vin_lst_6                bpchar(6) NOT NULL,
    phh_ast_id               bpchar(12) NOT NULL,
    invy_sta_ind             bpchar(1) NOT NULL,
    prod_clas                bpchar(2) NOT NULL,
    prod_line                bpchar(4) NOT NULL,
    mod_yr                   bpchar(2) NOT NULL,
    nmpl                     bpchar(25) NOT NULL,
    series                   bpchar(20) NOT NULL,
    model                    bpchar(20) NOT NULL,
    mod_cd                   bpchar(10) NOT NULL,
    cyl                      numeric(2)     NOT NULL,
    pwr_seat_cd              bpchar(1) NOT NULL,
    pwr_str_cd               bpchar(1) NOT NULL,
    pwr_brk_cd               bpchar(1) NOT NULL,
    pwr_lck_cd               bpchar(1) NOT NULL,
    pwr_wndw_cd              bpchar(1) NOT NULL,
    tnt_gls_cd               bpchar(1) NOT NULL,
    crz_cntrl_cd             bpchar(1) NOT NULL,
    tlt_whl_cd               bpchar(1) NOT NULL,
    radio_cd                 bpchar(1) NOT NULL,
    trans_typ_cd             bpchar(1) NOT NULL,
    trans_spds               bpchar(2) NOT NULL,
    eng_cd                   bpchar(1) NOT NULL,
    doors                    bpchar(1) NOT NULL,
    ac_cd                    bpchar(1) NOT NULL,
    dfrst_cd                 bpchar(1) NOT NULL,
    vt_cd                    bpchar(1) NOT NULL,
    no_of_comp               numeric(1)     NOT NULL,
    mfg_sell_dlr             bpchar(10) NOT NULL,
    sell_dlr_eeo             bpchar(1) NOT NULL,
    sell_dlr_fee             numeric(11, 2) NOT NULL,
    mfg_dlv_dlr              bpchar(10) NOT NULL,
    dlv_dlr_eeo              bpchar(1) NOT NULL,
    dlv_dlr_fee              numeric(11, 2) NOT NULL,
    dlv_phh_dlr_no           bpchar(5) NOT NULL,
    sel_phh_dlr_no           bpchar(5) NOT NULL,
    dlv_dlr_dlan             bpchar(5) NOT NULL,
    dlv_typ                  bpchar(1) NOT NULL,
    trk_key_no               bpchar(6) NOT NULL,
    ign_key_no               bpchar(6) NOT NULL,
    hvut_cd                  bpchar(1) NOT NULL,
    hp                       numeric(4, 1)  NOT NULL,
    shp_wt                   numeric(5)     NOT NULL,
    gvwr                     numeric(5)     NOT NULL,
    whl_bas                  numeric(3)     NOT NULL,
    brk_cd                   bpchar(1) NOT NULL,
    tcv_audit_insert_date    timestamp(6)   NOT NULL,
    tcv_audit_insert_userid  varchar(30)    NOT NULL,
    tcv_audit_insert_program varchar(30)    NOT NULL,
    tcv_audit_update_date    timestamp(6) NULL,
    tcv_audit_update_userid  varchar(30) NULL,
    tcv_audit_update_program varchar(30) NULL,
    CONSTRAINT mast_unit_pkey PRIMARY KEY (dlr_asgn_no)
);

CREATE INDEX mast_unit_ca_i03 ON sysusr.mast_unit (repl_client_no, repl_unit_no, corp_cd);
CREATE INDEX mast_unit_ca_idx1 ON sysusr.mast_unit (corp_cd, client_no, unit_no);
CREATE INDEX mast_unit_ca_idx2 ON sysusr.mast_unit (client_no, unit_no);
CREATE INDEX tcv_audit_insert_date_ca_idx1 ON sysusr.mast_unit (tcv_audit_insert_date);
CREATE INDEX tcv_audit_update_date_ca_idx1 ON sysusr.mast_unit (tcv_audit_update_date);

CREATE TABLE sysusr.ast_id_mapping
(
    corp_cd              bpchar(2) NOT NULL,
    dan                  bpchar(9) NOT NULL,
    spin_asset_id        int4        NOT NULL,
    edb_asset_id         int4        NOT NULL,
    audit_insert_dt      timestamp   NOT NULL,
    audit_insert_login   varchar(30) NOT NULL,
    audit_insert_pgm     varchar(30) NOT NULL,
    audit_update_dt      timestamp NULL,
    audit_update_login   varchar(30) NULL,
    audit_update_pgm     varchar(30) NULL,
    ast_del_from_src_ind bpchar(1) NOT NULL,
    CONSTRAINT ast_id_mapping_edb_asset_id_check CHECK (((edb_asset_id >= 0) AND (edb_asset_id <= 999999999))),
    CONSTRAINT ast_id_mapping_pkey PRIMARY KEY (spin_asset_id),
    CONSTRAINT ast_id_mapping_spin_asset_id_check CHECK (((spin_asset_id >= 0) AND (spin_asset_id <= 999999999)))
);

CREATE INDEX ast_id_mapping_i02 ON sysusr.ast_id_mapping USING btree (dan, corp_cd, ast_del_from_src_ind);
CREATE INDEX ast_id_mapping_i03 ON sysusr.ast_id_mapping USING btree (edb_asset_id);

CREATE TABLE sysusr.shared_inv
(
    client_no              bpchar(8) NOT NULL,
    unit_no                bpchar(8) NOT NULL,
    unit_curr_stat         bpchar(1) NOT NULL,
    unit_prev_stat         bpchar(1) NOT NULL,
    xref_curr_stat         bpchar(1) NOT NULL,
    xref_prev_stat         bpchar(1) NOT NULL,
    xref_client_no         bpchar(8) NOT NULL,
    xref_unit_no           bpchar(8) NOT NULL,
    purchase_type          bpchar(1) NOT NULL,
    mfg_order_no           bpchar(10) NOT NULL,
    initial_cost           numeric(9, 2)  NOT NULL,
    book_value             numeric(11, 2) NOT NULL,
    lease_term             bpchar(3) NOT NULL,
    lev_lease_type         bpchar(1) NOT NULL,
    billing_yr             numeric(2)     NOT NULL,
    billing_mo             numeric(2)     NOT NULL,
    ec_lt_accid_exp        numeric(4)     NOT NULL,
    ec_lt_maint_exp        numeric(4)     NOT NULL,
    ec_odometer            numeric(6)     NOT NULL,
    lease_co_owned         bpchar(1) NOT NULL,
    initial_record         bpchar(1) NOT NULL,
    sub_no                 bpchar(2) NOT NULL,
    div_no                 bpchar(2) NOT NULL,
    branch_no              bpchar(3) NOT NULL,
    finance_source         bpchar(3) NOT NULL,
    vin                    bpchar(17) NOT NULL,
    unit_type              bpchar(2) NOT NULL,
    car_mfg_code           bpchar(2) NOT NULL,
    car_make_code          bpchar(2) NOT NULL,
    car_model_yr           bpchar(2) NOT NULL,
    car_line_code          bpchar(1) NOT NULL,
    car_series_code        bpchar(1) NOT NULL,
    car_doors              bpchar(1) NOT NULL,
    car_body_style         bpchar(2) NOT NULL,
    car_cylinders          bpchar(1) NOT NULL,
    car_trans              bpchar(1) NOT NULL,
    car_radio              bpchar(1) NOT NULL,
    car_ps                 bpchar(1) NOT NULL,
    car_pb                 bpchar(1) NOT NULL,
    car_ac                 bpchar(1) NOT NULL,
    car_tinted_all         bpchar(1) NOT NULL,
    car_tinted_ws          bpchar(1) NOT NULL,
    car_vinyl_int          bpchar(1) NOT NULL,
    car_vinyl_roof         bpchar(1) NOT NULL,
    sell_dealer_no         bpchar(5) NOT NULL,
    buy_dealer_no          bpchar(5) NOT NULL,
    buy_region             bpchar(2) NOT NULL,
    buy_state_code         bpchar(2) NOT NULL,
    buy_city_code          bpchar(3) NOT NULL,
    buy_cnty_code          bpchar(3) NOT NULL,
    delivery_yr            numeric(2)     NOT NULL,
    delivery_mo            numeric(2)     NOT NULL,
    delivery_da            numeric(2)     NOT NULL,
    bill_sale_code         bpchar(1) NOT NULL,
    init_rent_yr           numeric(2)     NOT NULL,
    init_rent_mo           numeric(2)     NOT NULL,
    last_rent_yr           numeric(2)     NOT NULL,
    last_rent_mo           numeric(2)     NOT NULL,
    sold_yr                numeric(2)     NOT NULL,
    sold_mo                numeric(2)     NOT NULL,
    sold_da                numeric(2)     NOT NULL,
    title_reg_name         bpchar(30) NOT NULL,
    driv_name              bpchar(30) NOT NULL,
    driv_address           bpchar(30) NOT NULL,
    driv_city              bpchar(28) NOT NULL,
    driv_state             bpchar(2) NOT NULL,
    driv_zipcode           bpchar(6) NOT NULL,
    driv_buy_region        bpchar(2) NOT NULL,
    driv_state_code        bpchar(2) NOT NULL,
    driv_city_code         bpchar(3) NOT NULL,
    driv_cnty_code         bpchar(3) NOT NULL,
    driv_assign_yr         numeric(2)     NOT NULL,
    driv_assign_mo         numeric(2)     NOT NULL,
    driv_assign_da         numeric(2)     NOT NULL,
    rental_tax_code        bpchar(3) NOT NULL,
    ttl_ln_flag            bpchar(2) NOT NULL,
    ttl_filler1            bpchar(1) NOT NULL,
    ttl_psn_cd             bpchar(2) NOT NULL,
    ttl_filler2            bpchar(1) NOT NULL,
    ttl_brngp_ind          bpchar(1) NOT NULL,
    ttl_brngp_typ          bpchar(2) NOT NULL,
    ttl_filler3            bpchar(1) NOT NULL,
    ttl_brngp_mo           bpchar(3) NOT NULL,
    ttl_brngp_week         bpchar(1) NOT NULL,
    ttl_filler4            bpchar(1) NOT NULL,
    title_state            bpchar(2) NOT NULL,
    title_iss_yr           numeric(2)     NOT NULL,
    title_iss_mo           numeric(2)     NOT NULL,
    title_iss_da           numeric(2)     NOT NULL,
    title_ret_cli          bpchar(1) NOT NULL,
    title_inhouse          bpchar(1) NOT NULL,
    title_received         bpchar(1) NOT NULL,
    title_corr             bpchar(1) NOT NULL,
    title_dup_req          bpchar(1) NOT NULL,
    title_dup_rcv          bpchar(1) NOT NULL,
    title_iss_buyer        bpchar(1) NOT NULL,
    title_iss_cli          bpchar(1) NOT NULL,
    title_iss_ret          bpchar(1) NOT NULL,
    title_iss_driv         bpchar(1) NOT NULL,
    title_iss_c_a          bpchar(1) NOT NULL,
    phh_title_yr           numeric(2)     NOT NULL,
    phh_title_mo           numeric(2)     NOT NULL,
    phh_title_da           numeric(2)     NOT NULL,
    cli_stat_title         bpchar(1) NOT NULL,
    cli_stat_b_of_s        bpchar(1) NOT NULL,
    cli_stat_tx_afd        bpchar(1) NOT NULL,
    cli_stat_reg           bpchar(1) NOT NULL,
    cli_title_yr           numeric(2)     NOT NULL,
    cli_title_mo           numeric(2)     NOT NULL,
    cli_title_da           numeric(2)     NOT NULL,
    lic_plate_no           bpchar(20) NOT NULL,
    lic_state              bpchar(2) NOT NULL,
    lic_iss_yr             numeric(2)     NOT NULL,
    lic_iss_mo             numeric(2)     NOT NULL,
    lic_iss_da             numeric(2)     NOT NULL,
    cycle_no               bpchar(2) NOT NULL,
    cycle_no_latest        bpchar(2) NOT NULL,
    pw_no                  bpchar(3) NOT NULL,
    pw_no_latest           bpchar(3) NOT NULL,
    sale_reason            bpchar(1) NOT NULL,
    lease_rate             bpchar(4) NOT NULL,
    tax_paid_yr            bpchar(2) NOT NULL,
    tax_paid_state         bpchar(2) NOT NULL,
    tax_paid_city          bpchar(3) NOT NULL,
    tax_paid_cnty          bpchar(3) NOT NULL,
    filler                 bpchar(15) NOT NULL,
    eq_filler1             bpchar(4) NOT NULL,
    eq_model_yr            bpchar(2) NOT NULL,
    eq_ident1              bpchar(2) NOT NULL,
    eq_ident2              bpchar(2) NOT NULL,
    eq_ident3              bpchar(2) NOT NULL,
    eq_cost_class          bpchar(1) NOT NULL,
    eq_filler2             bpchar(8) NOT NULL,
    trk_mfg_code           bpchar(2) NOT NULL,
    trk_make_code          bpchar(2) NOT NULL,
    trk_model_yr           bpchar(2) NOT NULL,
    trk_style              bpchar(1) NOT NULL,
    trk_wb                 bpchar(1) NOT NULL,
    trk_weight             bpchar(1) NOT NULL,
    trk_engine             bpchar(1) NOT NULL,
    trk_displ              bpchar(1) NOT NULL,
    trk_trans              bpchar(1) NOT NULL,
    trk_axle               bpchar(1) NOT NULL,
    trk_ps                 bpchar(1) NOT NULL,
    trk_pb                 bpchar(1) NOT NULL,
    trk_trlr_make          bpchar(2) NOT NULL,
    trk_trlr_style         bpchar(2) NOT NULL,
    trk_spec_eq            bpchar(1) NOT NULL,
    trk_fhut_code          bpchar(1) NOT NULL,
    phh_inv_rcv_mo         bpchar(2) NOT NULL,
    phh_inv_rcv_yr         bpchar(2) NOT NULL,
    no_416_ind             bpchar(1) NOT NULL,
    tcv_audit_insert_dt    timestamp      NOT NULL,
    tcv_audit_insert_login varchar(30)    NOT NULL,
    tcv_audit_insert_pgm   varchar(30)    NOT NULL,
    tcv_audit_update_dt    timestamp NULL,
    tcv_audit_update_login varchar(30) NULL,
    tcv_audit_update_pgm   varchar(30) NULL,
    CONSTRAINT shared_inv_pk PRIMARY KEY (client_no, unit_no, unit_curr_stat, unit_prev_stat, xref_curr_stat,
                                          xref_prev_stat, book_value, billing_yr, billing_mo, ec_odometer, vin,
                                          driv_name, driv_address, driv_city, driv_state, driv_zipcode)
);

CREATE TABLE sysusr.org_id_mapping
(
    corp_cd              bpchar(2) NOT NULL,
    cli_no               varchar(8)  NOT NULL,
    spin_org_id          int4        NOT NULL,
    edb_org_id           int4        NOT NULL,
    audit_insert_dt      timestamp   NOT NULL,
    audit_insert_login   varchar(30) NOT NULL,
    audit_insert_pgm     varchar(30) NOT NULL,
    audit_update_dt      timestamp NULL,
    audit_update_login   varchar(30) NULL,
    audit_update_pgm     varchar(30) NULL,
    cli_del_from_src_ind bpchar(1) NOT NULL,
    CONSTRAINT org_id_mapping_edb_org_id_check CHECK (((edb_org_id >= 0) AND (edb_org_id <= 999999999))),
    CONSTRAINT org_id_mapping_pkey PRIMARY KEY (spin_org_id),
    CONSTRAINT org_id_mapping_spin_org_id_check CHECK (((spin_org_id >= 0) AND (spin_org_id <= 999999999)))
);
CREATE INDEX org_id_mapping_i02 ON sysusr.org_id_mapping USING btree (cli_no, corp_cd);
CREATE INDEX org_id_mapping_i03 ON sysusr.org_id_mapping USING btree (edb_org_id);

INSERT INTO sysusr.ast_id_mapping (spin_asset_id, corp_cd, dan, audit_insert_dt, audit_insert_login, audit_insert_pgm, ast_del_from_src_ind, edb_asset_id)
VALUES (13176770, 'FA', 'DAN1002', CURRENT_DATE, 'eapi', 'eapi', 'N', 93176770);

INSERT INTO sysusr.mast_unit (client_no, corp_cd, unit_no, cli_ast_no, repl_client_no, repl_unit_no, repl_cli_ast_no, cur_evt_seq_no, cur_evt, cur_evt_dt_c, cur_evt_dt_yr, cur_evt_dt_mo, cur_evt_dt_da, reqsn_no, cont_typ_cd, mo_reqd, emr_ind, ttl_cert_st, bkdn, ttl_own, ttl_co_nm, ttl_own_1st, ttl_own_mi, ttl_own_midrest, ttl_own_lst, ttl_addr1, ttl_addr2, ttl_city, ttl_cnty, ttl_st, ttl_zip, ttl_no, ttl_loc, ttl_iss_dt_c, ttl_iss_dt_yr, ttl_iss_dt_mo, ttl_iss_dt_da, tag_no, tag_iss_st, reg_xpir_dt_c, reg_xpir_dt_yr, reg_xpir_dt_mo, reg_xpir_dt_da, filler2, filler3, vin_decode_stat_cd, filler6, cli_drv_no, filler7, vndr_market_id, filler9, uvc, group_cd, drv_strt_dt_c, drv_strt_dt_yr, drv_strt_dt_mo, drv_strt_dt_da, dlr_asgn_no, fac_ord_no, vin_1st_9, vin_10_11, vin_lst_6, phh_ast_id, invy_sta_ind, prod_clas, prod_line, mod_yr, nmpl, series, model, mod_cd, cyl, pwr_seat_cd, pwr_str_cd, pwr_brk_cd, pwr_lck_cd, pwr_wndw_cd, tnt_gls_cd, crz_cntrl_cd, tlt_whl_cd, radio_cd, trans_typ_cd, trans_spds, eng_cd, doors, ac_cd, dfrst_cd, vt_cd, no_of_comp, mfg_sell_dlr, sell_dlr_eeo, sell_dlr_fee, mfg_dlv_dlr, dlv_dlr_eeo, dlv_dlr_fee, dlv_phh_dlr_no, sel_phh_dlr_no, dlv_dlr_dlan, dlv_typ, trk_key_no, ign_key_no, hvut_cd, hp, shp_wt, gvwr, whl_bas, brk_cd, tcv_audit_insert_date, tcv_audit_insert_userid, tcv_audit_insert_program, tcv_audit_update_date, tcv_audit_update_userid, tcv_audit_update_program)
VALUES ('CLI002', 'FA', '07392', '107392         ', '', '        ', '               ', 810, 'ACTIVE    ', 20, 23,         5, 17, ' ', '  ', '    ', ' ', '  ', '0000005455-001-000                        ',       '                                             ', '                                             ','               ', ' ', '              ', '                    ', '                              ', '                              ', '                    ', '                       ', '  ', '         ', '               ', ' ', 0, 0, 0, 0, 'CPJ6955             ', 'CN', 20, 24, 12, 31, ' ', '               ', '1','              ', 'A14215233           ', '                    ', '  ', '         ', '          ', '    ', 0, 0, 0, 0, 'DAN1002', '            ', '3GNAXWEG6', 'PS', '211531', 'UNKNOWN     ', '4', 'LT', 'CHEV', '23', 'EQUINOX                  ', 'RS                  ', '4D SUV AWD          ', '1XY26     ', 0, ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'A', '  ', ' ', ' ', ' ', ' ', ' ', 0, '          ', ' ', 0.00, '          ', ' ',0.00, '     ', '     ', '     ', ' ', '      ', '      ', ' ', 0.0, 0, 2100, 0, ' ', '2023-05-16 16:10:14.748', 'TC28230', 'XFC_WEB:Bulk-saveAsset', '2023-12-08 04:13:53.23496', ' ', ' ');

INSERT INTO sysusr.mast_unit_fin (dlr_asgn_no, corp_cd, client_no, bkdn, unit_no, cli_ast_no, pur_typ_cd, loc_st_cd, loc_city_cd, loc_cnty_cd, cont_no, cont_typ, lse_typ, cli_yr_end, acc_mgt_svc_ind, flt_adm_svc_ind, flt_svc_ind, reimb_svc_ind, veh_rpt_svc_ind, cpn_bk_ind, mrm_svc_ind, fuel_svc_ind, ec_svc_ind, ins_svc_ind, bkdn_chrg_ind, rerg_svc_ind, bas_inv_amt, bas_inv_amt_typ, hldb_amt, sl_tax_amt, cli_prc_amt, unit_prc_amt, vnd_inv_amt, rebat_amt, drv_pd_opt_amt, intrm_int_ind, tot_cap_cst, tot_aqstn_cst, lndr_no, lsor_no, fin_src, fs_int_rt_ind, src_of_fnd, rnt_tax_pay_cd, bs_cst, bs_typ, cur_bk_val, cur_odom, cur_odom_c, cur_odom_yr, cur_odom_mo, cur_odom_da, in_svc_c, in_svc_yr, in_svc_mo, in_svc_da, mo_in_svc, calc_pref_cd, cum_dif_ind, lse_term, lse_bill_cyc, lse_rt_typ, lse_int_rt, int_rt_max, pref_int_rt_ind, prc_sbsdy, bill_int_rt_ind, lndr_yr_cd, prc_id, prc_eff_c, prc_eff_yr, prc_eff_mo, prc_eff_da, var_prc_ind, lse_depr_ovrd, adj_depr_pct, init_rnt_c, init_rnt_yr, init_rnt_mo, init_rnt_da, lst_rnt_c, lst_rnt_yr, lst_rnt_mo, lst_rnt_da, init_bill_c, init_bill_yr, init_bill_mo, init_bill_da, lst_bill_c, lst_bill_yr, lst_bill_mo, lst_bill_da, era_svc_ind, itc_pct, incc_svc_ind, inpl_svc_ind, mgt_fee, mgt_fee_ind, addl_mgt_fee, addl_mgt_ind, mgt_fee_max, post_term_fee, post_term_ind, rsdl_bk_val, lst_mo_amrt, cur_mo_amrt, nxt_mo_amrt, ytd_amrt, cli_ytd_amrt, ltd_amrt, lst_mo_int, cur_mo_int, nxt_mo_int, ytd_int, cli_ytd_int, ltd_int, lst_mo_rnt_tax, cur_mo_rnt_tax, nxt_mo_rnt_tax, ytd_rnt_tax, cli_ytd_rnt_tax, ltd_rnt_tax, lst_mo_mgt_fee, cur_mo_mgt_fee, nxt_mo_mgt_fee, ytd_mgt_fee, cli_ytd_mgt_fee, ltd_mgt_fee, phh_split, sell_fee, tot_cown_bill, otr_amrt, cum_dif, ytd_int_var, cmpnd_int, otr_c, otr_yr, otr_mo, otr_da, sl_typ, sl_c, sl_yr, sl_mo, sl_da, sl_amt, sld_tax_amt, sld_tax_loc, fin_hst_cr_c, fin_hst_cr_yr, fin_hst_cr_mo, fin_hst_cr_da, bkdn_eff_c, bkdn_eff_yr, bkdn_eff_mo, bkdn_eff_da, cli_pd_opt_amt, ir_svc_ind, interim_rent_ind, rt_attr_c, rt_attr_yr, rt_attr_mo, rt_attr_da, pu_svc_ind, ext_lease_ind, unit_addl_int_amt, addl_int_effdt_cc, addl_int_effdt_yy, addl_int_effdt_mm, addl_int_effdt_dd, fund_ind, cap_freeze_ind, term_type, maturity_date_cc, maturity_date_yy, maturity_date_mm, maturity_date_dd, tcv_audit_insert_date, tcv_audit_insert_userid, tcv_audit_insert_program, tcv_audit_update_date, tcv_audit_update_userid, tcv_audit_update_program)
VALUES('DAN1002', 'FA', 'CLI002', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, '', 0, 0, 0, 0, 0, 0, 0, '', 0, 0, '', '', '', '', '', '', 0, '', 0, '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', 0, 0, '', 0, '', '', '', 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, '', '', 0, '', 0, '', 0, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, 0, 0, '', '', 0, 0, 0, 0, '', '', 0, '', '', '', '', '', '', '', '', '', '', '', CURRENT_TIMESTAMP, '', '', CURRENT_TIMESTAMP, '', '');

INSERT INTO sysusr.shared_inv (client_no, unit_no, unit_curr_stat, unit_prev_stat, xref_curr_stat, xref_prev_stat, xref_client_no, xref_unit_no, purchase_type, mfg_order_no, initial_cost, book_value, lease_term, lev_lease_type, billing_yr, billing_mo, ec_lt_accid_exp, ec_lt_maint_exp, ec_odometer, lease_co_owned, initial_record, sub_no, div_no, branch_no, finance_source, vin, unit_type, car_mfg_code, car_make_code, car_model_yr, car_line_code, car_series_code, car_doors, car_body_style, car_cylinders, car_trans, car_radio, car_ps, car_pb, car_ac,car_tinted_all, car_tinted_ws, car_vinyl_int, car_vinyl_roof, sell_dealer_no, buy_dealer_no, buy_region, buy_state_code, buy_city_code, buy_cnty_code, delivery_yr, delivery_mo, delivery_da, bill_sale_code, init_rent_yr, init_rent_mo, last_rent_yr, last_rent_mo, sold_yr, sold_mo, sold_da, title_reg_name, driv_name, driv_address, driv_city, driv_state, driv_zipcode, driv_buy_region, driv_state_code, driv_city_code, driv_cnty_code, driv_assign_yr, driv_assign_mo, driv_assign_da, rental_tax_code, ttl_ln_flag, ttl_filler1, ttl_psn_cd, ttl_filler2, ttl_brngp_ind, ttl_brngp_typ, ttl_filler3, ttl_brngp_mo, ttl_brngp_week, ttl_filler4, title_state, title_iss_yr, title_iss_mo, title_iss_da, title_ret_cli, title_inhouse, title_received, title_corr, title_dup_req, title_dup_rcv, title_iss_buyer, title_iss_cli, title_iss_ret, title_iss_driv, title_iss_c_a, phh_title_yr, phh_title_mo, phh_title_da, cli_stat_title,cli_stat_b_of_s, cli_stat_tx_afd, cli_stat_reg, cli_title_yr, cli_title_mo, cli_title_da, lic_plate_no,lic_state, lic_iss_yr, lic_iss_mo, lic_iss_da, cycle_no, cycle_no_latest, pw_no, pw_no_latest, sale_reason, lease_rate, tax_paid_yr, tax_paid_state, tax_paid_city, tax_paid_cnty, filler, eq_filler1, eq_model_yr, eq_ident1, eq_ident2, eq_ident3, eq_cost_class, eq_filler2, trk_mfg_code, trk_make_code, trk_model_yr, trk_style, trk_wb, trk_weight, trk_engine, trk_displ,trk_trans, trk_axle, trk_ps, trk_pb, trk_trlr_make, trk_trlr_style, trk_spec_eq, trk_fhut_code, phh_inv_rcv_mo, phh_inv_rcv_yr, no_416_ind, tcv_audit_insert_dt, tcv_audit_insert_login, tcv_audit_insert_pgm, tcv_audit_update_dt, tcv_audit_update_login, tcv_audit_update_pgm)
VALUES ('CLI002', '07392', '', '', '', '', '', '', '', '', 0.00, 0.00, '', '', 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0, 0, 0, '', 0, 0, 0, 0, 0, 0, 0, '', '', '', '', '', '', '', '', '', '', 23, 12, 30, '', '', '', '', '', '', '', '', '', '', '', '', 12, 12, 12, '', '', '', '', '', '', '', '', '', '', '', 12, 12, 12, '', '', '', '', 12, 12, 12, '', '', 12, 12, 12, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '2023-12-08 04:13:53.23496', '', '', NULL, NULL, NULL);

INSERT INTO sysusr.driver (driv_nm_last, driv_nm_first, driv_nm_midinit, driv_nm_midrest, cli_driv_no, company_name, driv_addr1, driv_addr2, driv_city, driv_cnty, driv_state, driv_zipcode, driv_phone_area, driv_phone_no, driv_phone_extn, corp_cd, client_no, unit_no, soundex_last, soundex_first, tcv_audit_insert_date, tcv_audit_insert_userid, tcv_audit_insert_program, tcv_audit_update_date, tcv_audit_update_userid, tcv_audit_update_program)
VALUES ('', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'FA', 'CLI002', '07392', '', '', CURRENT_TIMESTAMP, '', '', NULL, NULL, NULL);

INSERT INTO sysusr.org_id_mapping (corp_cd, cli_no, spin_org_id, edb_org_id, audit_insert_dt, audit_insert_login, audit_insert_pgm, cli_del_from_src_ind)
VALUES ('FA', 'CLI002', 20268, 467021, CURRENT_TIMESTAMP, '', '', 'N');
